### ISSUE TITLE
Suggestion for website links

### ISSUE THREAD

**Issue by aaditkamat** [nus-cs2103-AY1819S1/cs2103-website#8]
I would like to suggest a feature for the module page where the links (such as the one shown below)  open a new tab upon being clicked instead of displaying content on the same tab, so that the user can just close the new tab to return back to the original module page. I hope this feature is useful for other students too. The CSS selector that I found on W3Schools for the accessing the links is  **a[href^="https"]**

![image](https://user-images.githubusercontent.com/30969577/44669237-eff9d280-aa51-11e8-895c-b07242c0bdad.png)

**Comment by aaditkamat** [comment]
I would like to know from other students too if this would be a useful feature to implement.

**Comment by damithc** [comment]
This is a good suggestion @aaditkamat In fact it has been in our minds for a while too.
The problem is our [website generator tool](https://markbind.github.io/markbind/) is based on the [Markdown syntax](https://guides.github.com/features/mastering-markdown/) which doesn't have a way to specify links to open in a new tab. Apparently, that's a design decision Markdown creators made to keep the syntax simple. The expectation is that users will use <kbd>Ctrl</kbd>+`Click` when they want to open a link in a new tab.

**Comment by aaditkamat** [comment]
I wasn't sure if the MarkBind tool allowed this UI change in the same way as jQuery. Thank you for your response Prof Damith.

**Comment by damithc** [comment]
> I wasn't sure if the MarkBind tool allowed this UI change in the same way as jQuery.

Actually, it _can_ be done in MarkBind (and even in Markdown, upon which MarkBind is based) but it is not supported natively. Here's the difference in source code.

Open link in same window (using markdown syntax):
```markdown
[Link text](http://link.url)
```

Open link in new window (needs to use plain HTML as no native support in Markdown):
```html
<a href="http://link.url" target="_blank">Link text</a>
```

Based on their native support for one but not the other, markdown seems to lean towards opening links in the same page. As the current thinking in the community seems to lean that way too ([example](https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba)), we decided to follow the same and use the simpler syntax for links.
